"""Turns the wasm2js ES module into a classic script that defines globalThis.RefCore.call(cmd) -> result.

The six WASI imports the C++ runtime links are stubbed: the rules never touch files, the clock or stdout.
"""
import re
import sys

src, dst = sys.argv[1], sys.argv[2]
code = open(src, encoding="utf-8").read()
code = re.sub(r"^import \* as wasi_snapshot_preview1 from 'wasi_snapshot_preview1';\s*", "", code, flags=re.M)
tail = code.index("var retasmFunc = asmFunc(")
body = code[:tail]
wrapper = r"""
// GENERATED by web/tools/build_core.sh from RefereeCareer/Source/RefereeCareer/*/RefCore and web/wasm/RcWebApi.cpp.
// Do not edit: change the C++ and rebuild.
(function () {
%BODY%
  var wasi_snapshot_preview1 = {
    fd_close: function () { return 0; },
    fd_prestat_get: function () { return 8; },
    fd_prestat_dir_name: function () { return 8; },
    fd_seek: function () { return 70; },
    fd_write: function () { return 8; },
    proc_exit: function (code) { throw new Error("RefCore aborted (" + code + ")"); }
  };
  var core = asmFunc({ "wasi_snapshot_preview1": wasi_snapshot_preview1 });
  core._initialize();
  var encoder = new TextEncoder();
  var decoder = new TextDecoder();
  function call(request) {
    var bytes = encoder.encode(typeof request === "string" ? request : JSON.stringify(request));
    var ptr = core.rc_alloc(bytes.length);
    var heap = new Uint8Array(core.memory.buffer);
    heap.set(bytes, ptr);
    heap[ptr + bytes.length] = 0;
    var out = core.rc_call(ptr);
    core.rc_free(ptr);
    var len = core.rc_result_length();
    var text = decoder.decode(new Uint8Array(core.memory.buffer, out, len));
    return JSON.parse(text);
  }
  globalThis.RefCore = { call: call };
})();
"""
open(dst, "w", encoding="utf-8").write(wrapper.replace("%BODY%", body))
print("wrote", dst)
